// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1eGpktblIAOrI68tgPxCq9Fsa1xdSXI',
    appId: '1:759556546667:web:9cd21fba85ac5d29e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    authDomain: 'while-2.firebaseapp.com',
    databaseURL: 'https://while-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'while-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUsLcgtaEnKKzXNYMhpzP7zkVZFmh_rk',
    appId: '1:759556546667:android:d570617f3b0c9cc0e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    databaseURL: 'https://while-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'while-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Hxumu0O4bCtvK-GHr8h_FVL8svb9eag',
    appId: '1:759556546667:ios:72784399a1009388e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    databaseURL: 'https://while-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'while-2.appspot.com',
    androidClientId: '759556546667-j2kme5o36er31ic5jqfbfj1q0ejmlae1.apps.googleusercontent.com',
    iosClientId: '759556546667-pmd1589sivqg4sgosaf7ev5q0r4e549b.apps.googleusercontent.com',
    iosBundleId: 'com.example.whileAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Hxumu0O4bCtvK-GHr8h_FVL8svb9eag',
    appId: '1:759556546667:ios:0f16ce2603fada78e3912e',
    messagingSenderId: '759556546667',
    projectId: 'while-2',
    databaseURL: 'https://while-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'while-2.appspot.com',
    androidClientId: '759556546667-j2kme5o36er31ic5jqfbfj1q0ejmlae1.apps.googleusercontent.com',
    iosClientId: '759556546667-vkktdqfr9idfom67sebl5ao6af8e45kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.whileAdmin.RunnerTests',
  );
}
